### Make file ###

ARDUINO_DIR   = /usr/share/arduino
ARDMK_DIR     = /home/willoliveira/.arduino_mk
#AVR_TOOLS_DIR = /usr

BOARD_TAG     = mega
BOARD_SUB     = atmega2560
MONITOR_PORT  = /dev/ttyACM0
include /home/willoliveira/.arduino_mk/Arduino.mk
